apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: transaction-requests
type: Opaque
stringData:
  url: https://api.restful-api.dev/objects
  user: <base64-encoded-user>
  token: <base64-encoded-token>
