apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-configmaps
  namespace: transaction-requests
spec:
  schedule: "*/5 * * * *" # Every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: configmap-checker
            image: your-cronjob-image
            env:
            - name: API_URL
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: url
            - name: API_USER
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: user
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: token
            - name: S3_URL
              valueFrom:
                secretKeyRef:
                  name: s3-secrets
                  key: url
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secrets
                  key: access_key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secrets
                  key: secret_key
          restartPolicy: OnFailure
